import type { Metadata } from "next";
import { Jua } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@propelauth/nextjs/client";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const jua = Jua({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jua",
  weight: ["400"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
    title: "Fluently",
    description: "Generated by create next app",
>>>>>>> b0eb0190ddd90b4c0c34cefa4b5314d51562cd87
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL}>
                <body className={`${poppins.className}  antialiased`}>
                    {children}
                </body>
            </AuthProvider>
        </html>
    );
}
