import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@propelauth/nextjs/client";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// const jua = Jua({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-jua",
//   weight: ["400"],
// });

export const metadata: Metadata = {
  title: "Fluently",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider authUrl={process.env.NEXT_PUBLIC_AUTH_URL}>
        <body className={`${poppins.className} antialiased`}>{children}</body>
      </AuthProvider>
    </html>
  );
}
